import { BlockGraph, BlockNode } from '../types';
import { TokenEstimator } from '../utils/token-estimator';

export class AiContextGenerator {
    static generate(graph: BlockGraph, projectName: string): string {
        let md = `# AI Project Context: ${projectName}\n\n`;
        md += `> This file is auto-generated by Hybrid-RCP. It provides a structured view of the project architecture for LLMs (Gemini, ChatGPT, Claude).\n\n`;

        // 1. System Overview (The Graph)
        md += `## 1. System Architecture (High-Level Graph)\n\n`;
        md += `**Nodes:** ${graph.nodes.length} | **Edges:** ${graph.edges.length}\n\n`;

        // Tree View
        md += `### Module Hierarchy\n`;
        md += `\`\`\`\n`;

        // Use a Set to track printed nodes to avoid duplicates if multiple criteria match
        const printed = new Set<string>();

        // Heuristic: Just list all nodes sorted by depth
        const sortedNodes = [...graph.nodes].sort((a, b) => (a.depth || 0) - (b.depth || 0));

        sortedNodes.forEach(node => {
            if (!printed.has(node.id)) {
                const indent = '  '.repeat(node.depth || 0);
                const tokenCount = node.compilationCost ? TokenEstimator.format(node.compilationCost * 15) : '?';
                md += `${indent}- [${node.type.toUpperCase()}] ${node.name} (${tokenCount})\n`;
                printed.add(node.id);
            }
        });
        md += `\`\`\`\n\n`;

        // 2. Interface Contracts (Public APIs)
        md += `## 2. Module Contracts (Public Interfaces)\n\n`;
        graph.nodes.forEach(node => {
            // Only show nodes with meaningful data/outputs
            if ((node.outputs && node.outputs.length > 0) || (node.data && node.data.length > 0)) {
                md += `### ${node.name}\n`;
                md += `**Type:** ${node.type} | **Path:** \`${node.filePath || 'inline'}\`\n\n`;

                if (node.data && node.data.length > 0) {
                    md += `**Data Structures:**\n`;
                    node.data.forEach(d => {
                        md += `- \`${d.type} ${d.name}\` ${d.isPublic ? '(pub)' : ''}\n`;
                    });
                    md += `\n`;
                }

                if (node.outputs && node.outputs.length > 0) {
                    md += `**Capabilities (Functions/Methods):**\n`;
                    node.outputs.forEach(out => {
                        const mutable = out.isMutable ? 'mut' : 'immut';
                        const ref = out.isReference ? '&' : '';
                        md += `- \`${out.name}(${out.args || ''}) -> ${out.type}\` [${mutable}${ref ? ', ref' : ''}]\n`;
                    });
                    md += `\n`;
                }
                md += `---\n`;
            }
        });

        // 3. Dependency Graph (Edges)
        md += `## 3. Dependency Graph (Flow)\n\n`;
        md += `| Source | Relationship | Target | Notes |\n`;
        md += `|---|---|---|---|\n`;
        graph.edges.forEach(edge => {
            const src = edge.from.split('/').pop() || edge.from;
            const tgt = edge.to.split('/').pop() || edge.to;
            let icon = '➡️';
            if (edge.type === 'mutable') icon = '✏️ (Mut)';
            if (edge.type === 'ownership') icon = 'owns';
            if (edge.type === 'conflict') icon = '❌ (CONFLICT)';

            md += `| ${src} | ${icon} | ${tgt} | ${edge.label || ''} |\n`;
        });
        md += `\n`;

        // 4. Conflicts & Action Items
        if (graph.conflicts && graph.conflicts.length > 0) {
            md += `## 4. Active Conflicts (Action Items)\n\n`;
            graph.conflicts.forEach(c => {
                md += `### 🔴 ${c.id}\n`;
                md += `**Severity:** ${c.severity.toUpperCase()}\n`;
                md += `**Description:** ${c.description}\n`;
                md += `**Fix:** ${c.suggestedFix || 'Investigate manually.'}\n\n`;
            });
        } else {
            md += `## 4. Active Conflicts\n`;
            md += `✅ System is clean. No structural conflicts detected.\n`;
        }

        return md;
    }
}
