import * as path from 'path';
import { IFileSystem } from './utils/filesystem';
import { CargoManager } from './cargo-manager';
import { IUserInterface } from './ui-interface';

export class BlockManager {
    private fileSystem: IFileSystem;
    private cargoManager?: CargoManager;
    private ui?: IUserInterface;

    constructor(fileSystem: IFileSystem, cargoManager?: CargoManager, ui?: IUserInterface) {
        this.fileSystem = fileSystem;
        this.cargoManager = cargoManager;
        this.ui = ui;
    }

    async createBlock(parentFilePath: string, blockName: string, type: 'file' | 'folder'): Promise<string> {
        const fileSystem = this.fileSystem;

        // 1. Validate inputs
        if (!/^[a-z0-9_]+$/.test(blockName)) {
            throw new Error(`Invalid block name '${blockName}'. Must be snake_case (a-z0-9_).`);
        }

        // 2. Check if parent exists
        if (!await fileSystem.exists(parentFilePath)) {
            throw new Error(`Parent file '${parentFilePath}' does not exist.`);
        }

        // 3. Determine new file path
        const parentDir = path.dirname(parentFilePath);
        let newFilePath: string;
        let newDirPath: string | undefined;

        if (type === 'file') {
            newFilePath = path.join(parentDir, `${blockName}.rs`);
        } else {
            // For folder modules: parent/block_name/mod.rs
            newDirPath = path.join(parentDir, blockName);
            newFilePath = path.join(newDirPath, 'mod.rs');
        }

        // 4. Check if new block already exists
        if (await fileSystem.exists(newFilePath)) {
            throw new Error(`Block '${blockName}' already exists at ${newFilePath}.`);
        }

        // 5. Update Parent File (add `pub mod block_name;`)
        const parentContent = await fileSystem.readFile(parentFilePath);
        const modDecl = `pub mod ${blockName};`;

        if (!parentContent.includes(`mod ${blockName};`)) {
            // Simple insertion strategy:
            // If there are existing mod declarations, append after the last one.
            // Otherwise, append to the end of file (or top if empty).
            // For MVP, we'll just append to the end of the file or after imports.

            // Refined: Append at the end of the file for now.
            const newParentContent = parentContent.endsWith('\n')
                ? `${parentContent}${modDecl}\n`
                : `${parentContent}\n${modDecl}\n`;

            await fileSystem.writeFile(parentFilePath, newParentContent);
        }

        // 6. Create the new file/folder
        if (type === 'folder' && newDirPath && fileSystem.mkdir) {
            await fileSystem.mkdir(newDirPath);
        }

        // 7. Write Template Content
        const template = `// Block: ${blockName}
// Auto-generated by Hybrid-RST

pub struct ${this.toPascalCase(blockName)} {
    // data fields
}

impl ${this.toPascalCase(blockName)} {
    pub fn new() -> Self {
        Self {}
    }
}

// TODO: Implement SubBlock trait if needed
/*
pub trait SubBlock {
    type Input;
    type Output;
    fn execute(&mut self, data: Self::Input) -> Self::Output;
}
*/
`;
        await fileSystem.writeFile(newFilePath, template);

        // 8. Auto-Inject Dependencies (AI Audit)
        if (this.cargoManager) {
            const projectRoot = await this.findProjectRoot(parentFilePath);
            if (projectRoot) {
                const cargoPath = path.join(projectRoot, 'Cargo.toml');
                let depsToAdd: { name: string, version: string, features?: string[] }[] = [];

                // Heuristics
                if (blockName.includes('db') || blockName.includes('sql') || blockName.includes('database')) {
                    console.log(`AI Audit: Detected database-related block '${blockName}'. Adding 'sqlx' and 'tokio'.`);
                    depsToAdd.push({ name: 'sqlx', version: '0.6', features: ['runtime-tokio-rustls', 'postgres'] });
                    depsToAdd.push({ name: 'tokio', version: '1.0', features: ['full'] });
                }

                if (blockName.includes('api') || blockName.includes('web') || blockName.includes('server')) {
                    console.log(`AI Audit: Detected web-related block '${blockName}'. Adding 'axum' and 'tokio'.`);
                    depsToAdd.push({ name: 'axum', version: '0.6' });
                    depsToAdd.push({ name: 'tokio', version: '1.0', features: ['full'] });
                }

                if (depsToAdd.length > 0) {
                    let shouldAdd = true;
                    if (this.ui) {
                        const message = `AI Audit detected dependencies for '${blockName}': ${depsToAdd.map(d => d.name).join(', ')}. Add to Cargo.toml?`;
                        const selection = await this.ui.showInformationMessage(message, 'Yes', 'No');
                        // In CLI consoleUI, it returns undefined (auto-yes for MVP) unless we change it.
                        // But for VS Code, it returns the string.
                        // If selection is undefined (CLI default), treat as yes.
                        if (selection !== 'Yes' && selection !== undefined) {
                            shouldAdd = false;
                        }
                    }

                    if (shouldAdd && this.cargoManager) {
                        for (const dep of depsToAdd) {
                            await this.cargoManager.addDependency(cargoPath, dep.name, dep.version, dep.features);
                        }
                    }
                }
            }
        }

        return newFilePath;
    }

    private toPascalCase(str: string): string {
        return str.replace(/(^|_)([a-z])/g, (g) => g.slice(-1).toUpperCase());
    }

    private async findProjectRoot(startPath: string): Promise<string | null> {
        let currentDir = path.dirname(startPath);
        // Safety break for root
        while (path.dirname(currentDir) !== currentDir) {
            const cargoPath = path.join(currentDir, 'Cargo.toml');
            if (await this.fileSystem.exists(cargoPath)) {
                return currentDir;
            }
            currentDir = path.dirname(currentDir);
        }
        return null;
    }
}
